### ISSUE TITLE
useRememberedState Invalid number of arguments, expected 2

### ISSUE THREAD

**Issue by dsazup** [inertiajs/inertia-react#37]
Hello. From the docs looks like 2nd parameter in `useRememberedState` is optional, but at least php storm reports an error if you don't pass it. Looking at typescript declarations
```
 export function useRememberedState<RememberedState>(
    initialState: RememberedState,
    key: string
  ): [RememberedState, React.Dispatch<React.SetStateAction<RememberedState>>]
```

Looks like the `key` could be made optional, unless I am misunderstanding somethinng.

**Comment by MichaelDeBoey** [comment]
This is correct indeed.
#38 will close this 🙂
