### ISSUE TITLE
Use React Suspense API

### ISSUE THREAD

**Issue by ecreeth** [inertiajs/inertia-react#44]
Hey @sebastiandedeyne [Suspense API]

The default configuration is great, but I think that in the following way we can improve even more `inertia-react` using Suspense API.

I have configured my project as follows:

- I have normally installed inertia and inertia-react
- I have not changed anything in my webpack.mix.js file
- I have not configured `@babel/plugin-syntax-dynamic-import`
- I have added in resources / pages / {Welcome.js, About.js, Contact.js}
- I modified my web.php

My `app.js` file
```JSX
import React, { Suspense, lazy } from "react";
import { render } from "react-dom";
import { 
 InertiaApp, 
 InertiaLink as Link 
} from "@inertiajs/inertia-react";

const app = document.getElementById("app");

function App(props) {
  return (
    <main>
      <header>
        <Link href="/">Home</Link>
        <Link href="/about">About</Link>
        <Link href="/contact">Contact</Link>
      </header>

      <article>
        <Suspense fallback={<span className="loader" />}>
          <InertiaApp
            initialPage={JSON.parse(app.dataset.page)}
            resolveComponent={name =>
              lazy(() => import(`./pages/${name}`))
            }
          />
        </Suspense>
      </article>
    </main>
  );
}

render(<App />, app);
```
My Welcome.js file | Similar to `About.js` and `Contact.js`

```JSX
import React from 'react'

export default function Welcome(props) {
  return (
    <div>
      <h1>Welcome</h1>
      <p>Welcome to my first Inertia.js app!</p>
      <p>{props.foo}</p>
    </div>
  )
}
```
My `web.php` file

```PHP
Route::get('/', function () {
    return inertia('Welcome', [ 'foo' => 'This is the home page' ]);
});

Route::get('/about', function () {
    return inertia('About', [ 'foo' => 'This is the about page' ]);
});

Route::get('/contact', function () {
    return inertia('Contact', [ 'foo' => 'This is the contact page' ]);
});
```

My `webpack.mix.js` file

```JS
const mix = require('laravel-mix')

mix
  .react('resources/js/app.js', 'public/js')
  .sass('resources/sass/app.scss', 'public/css')
  .extract();
```

![Screenshot_2019-08-20_16-35-48](https://user-images.githubusercontent.com/20761166/63382426-b445d000-c368-11e9-85e2-fa7c8f911222.png)

**Comment by sebastiandedeyne** [comment]
Why close? :)

I like this idea, just haven't had the chance to experiment with it yet.

**Comment by ecreeth** [comment]
I have been playing with this and I have found better ways to do this and I would like to create a new issue with a better example. I really love inertiajs! :smile:
