### ISSUE TITLE
InertiaLink higher order component

### ISSUE THREAD

**Issue by dsazup** [inertiajs/inertia-react#45]
Hey all.

If I use 3rd party Button component, that turns into a link if I pass 'href' prop, I need to manually attach onClick listener and call Inertia.visit myself. 

I suppose I could also have my own Button component, that attaches onClick to the 3rd party and does Inertia.visit. Instead, it would be really nice if we could have something like `withInertia` higher order component. 

the usage would be something like this:

```
import {withInertia} from 'inertia-react';
import {Button} from '3rd-party-design-library';

const InertiaButton = withInertia(Button);

return (<div>
   <InertiaButton href="/">Hi</InertiaButton>
</div>);
```

What do you guys think?

**Comment by MichaelDeBoey** [comment]
The react community (and react team) is going forward towards hooks and tries to go away from HOCs and render functions, so I don't think we should still support it.

> If you’ve worked with React for a while, you may be familiar with patterns like render props and higher-order components that try to solve this. But these patterns require you to restructure your components when you use them, which can be cumbersome and make code harder to follow. If you look at a typical React application in React DevTools, you will likely find a “wrapper hell” of components surrounded by layers of providers, consumers, higher-order components, render props, and other abstractions.

https://reactjs.org/docs/hooks-intro.html

**Comment by dsazup** [comment]
Ok, I know what hooks are, but I don't think they solve the issue here, unless I am misunderstanding something?

So what would you say would be the best practice here, to attach my own onClick method every time or to create my own button component? Just looking for an advice here really. 

I don't see a problem with creating my own component, it's just a lot nicer to import all components from the design library that I use. And it would be nice if it worked out with Inertia out of the box.

**Comment by MichaelDeBoey** [comment]
I think creating your own wrapper component would be the thing to do.
Or that's what I would prefer to do anyway.

**Comment by sebastiandedeyne** [comment]
I'm very interested in looking for a more streamlined way to deal with cases like this!

Unfortunately I don't have any time this week, but I'm going to experiment with this later on.

**Comment by sebastiandedeyne** [comment]
I agree with @MichaelDeBoey that we should be wary of higher order components. I generally prefer hook-based solutions these days, although they still feel very new.

Something like this could be feasible, but I want to check out what others are doing first.

```js
import { Button } from '3rd-party-design-library';
import { useLink } from '@inertiajs/inertia-react';

const InertiaButton = ({ href, method, ...props }) => {
  return <Button {...props} {...useLink(href, { method })} />
};
```

**Comment by sebastiandedeyne** [comment]
Gonna hold off on this for now, we might revisit this in the future.
