### ISSUE TITLE
Best way to show a "loading" state when submitting form

### ISSUE THREAD

**Issue by andregoldstein** [inertiajs/inertia-react#54]
Hi guys, I'm trying to show a loading state when the form gets submitted via `Inertia.post`. I'm assuming the best way to do this is just to use React, for example using a React `useState` hook:

```
const [loading, setLoading] = useState(false);

const onSubmit = data => {
  setLoading(true);
  Inertia.post("/clients", data).finally(() => setLoading(false));
};
```

The problem is I'm getting a `Can't perform a React state update on an unmounted component` warning from React. I'm guessing my controller action redirect isn't giving the component chance to "clean up". Would be interested in hearing how others are handling loading states in React/Inertia.

Thanks!

**Comment by benvilliere** [comment]
I don’t see what’s wrong with your implementation. Could you share the jsx part too?

**Comment by andregoldstein** [comment]
Thanks @benvilliere it's a bit convoluted (apologies) but the actual React logic seems to work well, I was getting the impression that the React console warning was because of the Inertia redirect not allowing clean up of the React code but may be way out...

```
import React, { useState } from "react";
import { Inertia } from "@inertiajs/inertia";
import { useForm } from "react-hook-form";
import { usePage } from "@inertiajs/inertia-react";
import { showErrors } from "../../utils";
import Layout from "../Layout";

const ClientNew = () => {
  const { errors } = usePage();
  const { register, handleSubmit } = useForm();
  const [loading, setLoading] = useState(false);

  const onSubmit = data => {
    setLoading(true);
    Inertia.post("/clients", data).finally(() => setLoading(false));
  };

  return (
    <div>
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className="row">
          <div className="form-group col">
            <label>First Name</label>
            <input
              type="text"
              className="form-control"
              name="first_name"
              ref={register}
              autoFocus={true}
            />
            {showErrors(errors.first_name)}
          </div>
          <div className="form-group col">
            <label>Last Name</label>
            <input
              type="text"
              className="form-control"
              name="last_name"
              ref={register}
            />
            {showErrors(errors.last_name)}
          </div>
        </div>
        <div className="form-group">
          <label>Email</label>
          <input
            type="text"
            className="form-control"
            name="email"
            ref={register}
          />
          {showErrors(errors.email)}
        </div>

        <div className="form-group">
          <label>Staff Role</label>
          <select className="form-control" name="staff_role" ref={register}>
            <option value=""></option>
            <option value="Director">Director</option>
            <option value="CEO">CEO</option>
            <option value="Accounts">Accounts</option>
            <option value="Intern">Intern</option>
          </select>
          {showErrors(errors.staff_role)}
        </div>
        <button disabled={loading} className="btn btn-primary" type="submit">
          {loading ? "Submitting" : "Add client"}
        </button>
      </form>
    </div>
  );
};

ClientNew.layout = page => <Layout children={page} title="Add a client" />;

export default ClientNew;
```

**Comment by benvilliere** [comment]
I’d suspect this part ```<form onSubmit={handleSubmit(onSubmit)}>``` to be the cause.

Did you try this?

```<form onSubmit={event => handleSubmit(onSubmit)}>```

**Comment by andregoldstein** [comment]
Thanks, I think that is a `react-hook-form` pattern, I still seem to get the same error when calling it in the way you suggested.

**Comment by benvilliere** [comment]
I agree it doesn’t look like an Inertia problem. For what it’s worth here's a very similar working implementation (excepted from the useForm hook). 

`export default function Index() {
    const { app } = usePage()

    const [query, setQuery] = useState('')
    const [isLoading, setIsLoading] = useState(false)

    function handleSearch(event) {
        event.preventDefault()

        setIsLoading(true)

        axios.post('/explore', { search: query }).then(response => {
            setIsLoading(false)
	    ...
        })
    }

    return (
        <Layout>
                <Search
                    value={query}
                    onSubmit={event => handleSearch(event)}
                    onChange={event => setQuery(event.target.value)}
                />

                {isLoading &&
                    <Loader></Loader>
                }
                {! isLoading &&
                    <>...</>
                }
        </Layout>
    )
}`

**Comment by andregoldstein** [comment]
Thanks! Noticing you're using `axios` directly in your example as opposed to `Inertia.post` not sure if that will mean things behave differently?

**Comment by benvilliere** [comment]
Sorry I missed that, was too focused on the isLoading thing. I still think the Inertia call wouldn’t be the issue here though, but I might be wrong.

**Comment by andregoldstein** [comment]
Thanks, I think it's to do with the page "redirecting", I've had it happen using other tech with React and ended up having to do a full page refresh to get rid of the warning.

**Comment by sebastiandedeyne** [comment]
Hey @andregoldstein!

We just solved this exact problem in our app. Here's what we came up with:

```diff
 const [loading, setLoading] = useState(false);

 const onSubmit = data => {
   setLoading(true);
-  Inertia.post("/clients", data).finally(() => setLoading(false));
+  Inertia.post("/clients", data).catch(() => setLoading(false));
 };
```

When `Inertia.post` is _successful_ and the user gets redirected, you don't need to update `setLoading`. `setLoading` only needs to be updated when something goes wrong and the user is still in the same view as the `<Loader />` component.

That said, if you ever come across a situation where the above isn't an option, you can create a custom hook that only calls `setState` when the component is mounted.

```js
import { useEffect, useRef, useState } from 'react';

export default function useStateIfMounted(initialState) {
    const isMounted = useRef(true);

    useEffect(() => {
        return () => {
            isMounted.current = false;
        };
    }, []);

    const [state, setState] = useState(initialState);

    function setStateIfMounted(newState) {
        if (isMounted.current) {
            setState(newState);
        }
    }
    
    return [state, setStateIfMounted];
}
```

**Comment by andregoldstein** [comment]
Thanks @sebastiandedeyne will give that a look 👍

**Comment by brandoniffert** [comment]
Hey @sebastiandedeyne, I'm trying your `catch()` method that you mentioned working in your app. I'm using it in a basic login form, posting to Laravel's built-in `/login`. The problem I'm seeing is that the request is always a 200 response so Inertia/axios never actually calls the `catch()` function to unset loading. I'm going to try to implement your `useStateIfMounted` hook but was just wondering how you had the `catch()` method working in your app.

**Comment by sebastiandedeyne** [comment]
I'd need to know more about your application to properly diagnose this, but I assume your setup is dufferent.

**1. `setState` in the current page component**

```jsx
<Layout>
  <LoginPage /> {/* Loading indicator is here somewhere */}
</Layout>

{/* After login… */}

<Layout>
  <AnotherPage />
</Layout>
```

In this case, you don't need to `setLoading(false)` after a successful request, because `<LoginPage />` will be replaced by `<AnotherPage />` by Inertia after the user logged in.

**2. `setState` in a component that's persisted**

```jsx
<Layout> {/* Loading indicator is here somewhere */}
  <LoginPage />
</Layout>

{/* After login… */}

<Layout> {/* Loading indicator is still here somewhere */}
  <AnotherPage />
</Layout>
```

I assume this is what your code looks like.

In this case, you'd need to `setLoading(false)` after a successful request, because `<Layout />` maintains its state across requests (by default, `preserveState` is true for `POST` requests).

One way to solve this is by disabling `preserveState`, which forces `Layout` to rerender. However, you only want to do this when the request was successful.

```js
Inertia.post('/login', {
  preserveState: (page) => !!Object.keys(page.errors).length,
});
```

**Comment by brandoniffert** [comment]
Thanks @sebastiandedeyne, didn't realize `preserveState` could take a function, that pointed me the right direction
