### ISSUE TITLE
Contribution guide.

### ISSUE THREAD

**Issue by natsathorn** [inertiajs/inertia-react#58]
I would like to help adding unit tests to this project and later migrate to fully typed with Typescript.

However, there is no contribution guide provided just yet. 
There are some question I would like to ask.

- A place to find the development plan or discussion? 
- Currently, we don't have unit test now. How to properly test this package locally?
   _My previous PR is just a small change, so I copied the file and try it in my playground project._

**Comment by sebastiandedeyne** [comment]
Hi @natsathorn!

Thanks for wanting to contribute! These are things we're working on, and will probably have something formalized around the summer. We will definitely be adding tests, but migrating to TypeScript isn't planned at the moment.

As for answers to your questions:

- All development for this library gets discussed here on GitHub
- Unfortunately the only way to test this now is to manually check the code in an existing project. As I said, this is a temporary thing, and we're aiming to solve these problems by the summer
