### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by R3l4x3** [inertiajs/inertia-react#9]
After successfully using Inertia in combination with VueJS, I wanted to switch from VueJS to React today.

But no matter what I do, I can't get it to work. I followed the documentation and created/changed the files accordingly.

I have a warning if I use `npm run dev`:

```
WARNING in ./resources/js/Pages/Welcome.js 5:29-35
"export 'default' (imported as 'Layout') was not found in '@/Shared/Layout'
 @ ./resources/js/Pages lazy ^\.\/.*$ namespace object
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```

And this is the html output:

```html
<!DOCTYPE html>
  <html>
  <head>
  <meta charset="utf-8"/>
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
  />
  <link href="/css/app.css?id=d41d8cd98f00b204e980" rel="stylesheet">
  <script src="/js/app.js?id=31956b447ba54e84ae8e" defer></script>
  </head>
  <body>
    <div id="app" data-page="{&quot;component&quot;:&quot;Welcome&quot;,&quot;props&quot;:[],&quot;url&quot;:&quot;http:\/\/aldtool20.test&quot;,&quot;version&quot;:&quot;08a79a8cfa552283a2eba359e9a046bd&quot;}"></div>
  </body>
  </html>
```

Thank's for your help :)

**Comment by MichaelDeBoey** [comment]
@R3l4x3 You should export your `Layout` component.

I've made a PR (#10) to make the docs more copy/paste-able, so have a look there for the solution 😉

**Comment by R3l4x3** [comment]
Thank you @MichaelDeBoey , that worked! I actually thought I had tried it, but without success.
